services:
  tweet_collector:
    build: tweet_collector     # build it from dockerfile
    volumes:
    - ./tweet_collector/:/app
    depends_on:
    - mongodb

  mongodb:
    image: mongo
    ports:
    - 27017:27017

  etl:
    build: ./etl
    volumes:
    - ./etl/:/app
    depends_on:
      - mongodb
      - postgresdb

  postgresdb:
    image: postgres
    ports:
    - 5555:5432
    environment:
    - POSTGRES_USER=docker_user
    - POSTGRES_PASSWORD=1234
    - POSTGRES_DB=twitter


  slackbot:
    build: ./slackbot
    volumes:
    - ./slackbot/:/app
    depends_on:
    - postgresdb
